# Generated by Django 4.0.5 on 2022-07-29 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 29)),
        ),
    ]
